drop FUNCTION if EXISTS countBought();
drop FUNCTION if EXISTS price(numeric, numeric);
drop FUNCTION if EXISTS countTickets(VARCHAR);
drop FUNCTION IF EXISTS getTickets(VARCHAR);
drop VIEW IF EXISTS upcoming;
drop FUNCTION IF EXISTS manageLoginsFunc();

DROP TABLE IF EXISTS USERS CASCADE ;
DROP TABLE IF EXISTS PURCHASES CASCADE ;
DROP TABLE IF EXISTS LOGINS CASCADE ;
DROP TABLE IF EXISTS TICKETS CASCADE ;
DROP TABLE IF EXISTS EVENTS CASCADE ;
DROP TABLE IF EXISTS TICKET_KINDS CASCADE ;
DROP TABLE IF EXISTS CLIENTS_DISCOUNTS CASCADE ;
DROP TABLE IF EXISTS DISCOUNTS CASCADE ;
DROP TABLE IF EXISTS EVENT_Types CASCADE ;
DROP TABLE if exists LAST_LOGINS CASCADE;